### ISSUE TITLE
The script assigns 5% discount instead of 10% .

### ISSUE THREAD

**Issue by katejanis** [katejanis/learning#10]
Banking
Version 0.1
 Steps to reproduce:
"1) Run 'ruby run.rb' script;
2) Input  value 10000.00 and press enter."
Expected result:
The script assigns 10% discount.
Actual result:
The script assigns 5% discount.

**Comment by belgeu** [comment]
@katejanis please check if this is still relevant since in `banking-0.3` functionality has changed significantly. Thank you.

**Comment by katejanis** [comment]
@belgeu i checked and it fixed and works right . The script assigns 10% for 10000.00. Thank you.

**Comment by belgeu** [comment]
Great, thanks, closing the issue.
