### ISSUE TITLE
Script gives 3% discount for 20 years old customer

### ISSUE THREAD

**Issue by katejanis** [katejanis/learning#14]
## **_Banking v0.3_**

**Steps to reproduse**:
1) Run 'ruby run.rb' script;
2) Input customers age 20  and press enter; 
3) Input transaction value 99.99 and press enter; 
4) Input number of items 3 and press enter;

**Expected result:**
Customer service: _true_
Offer membership: _false_
Discount rate: _false_

**Actual result:**
Customer service: _true_
Offer membership: _false_
Discount rate: _**0.03**_

**Comment by belgeu** [comment]
@katejanis please do a re-test to verify the bug.
Thanks.
